dns:
  listen_ip: "0.0.0.0"
  listen_port: 8053

api:
  listen_ip: "0.0.0.0"
  listen_port: 8000

logic:
  default_policy: any
  timeout_sec: 60
  resolve_cache_ttl: 5

zones:
  - name: "failover"
    fallback_ttl: 30
    domains:
      webmail.failover:
        fallback_ip: "10.10.10.254"
        quorum: 2