dns:
  listen_ip: "0.0.0.0"
  listen_port: 8053
  resolve_cache_ttl: 5

api:
  listen_ip: "0.0.0.0"
  listen_port: 8000

zones:
  - name: "failover"
    domains:
      webmail.failover:
        fallback:
          - "10.10.10.254"
          - "10.10.10.253"
        server:
          policy: any
          timeout_sec: 60
        monitor:
          mode: tcp
          monitor_tag: test
          targets:
            - ip: 208.95.112.1
              port: 80
              priority: 5
            - ip: 34.117.59.81
              port: 80
              priority: 8
        agent:
          interval_sec: 10     # для агента
          timeout_sec: 5
          token: "secret_token"