dns:
  listen_ip: "0.0.0.0"
  listen_port: 8053

api:
  listen_ip: "0.0.0.0"
  listen_port: 8000

zones:
  - name: "failover"
    fallback_ttl: 30
    domains:
      webmail.failover:
        fallback_ip: "10.10.10.254"
        policy: any
        mode: tcp
        monitor_tag: test
        timeout_sec: 60
        resolve_cache_ttl: 5
        targets:
          - ip: 10.10.10.250
            port: 443
          - ip: 10.10.10.251
            port: 443